### ISSUE TITLE
Mark as answered appears broken

### ISSUE THREAD

**Issue by s1037989** [KeystoneIT/Ama#45]

**Comment by JDorpinghaus** [comment]
I am unable to reproduce the issue on the dev server, maybe I'm not understanding exactly what the issue is.

I created a question in one session and replied from another session:
![1](https://cloud.githubusercontent.com/assets/9485088/8653005/b209bbea-2947-11e5-9007-b125e4500834.PNG)

Then, in the first session, I chose a comment from the second session as the answer to my question:
![2](https://cloud.githubusercontent.com/assets/9485088/8653021/c7d4e33c-2947-11e5-8b21-fa8b23393111.PNG)

The question was appropriately marked as answered and jumped to the bottom of the page:
![3](https://cloud.githubusercontent.com/assets/9485088/8653053/e91ce9d6-2947-11e5-8f7d-b530ffc22921.PNG)

**Comment by s1037989** [comment]
Does this screen shot help?

![selection_219](https://cloud.githubusercontent.com/assets/517498/9961755/e809b28e-5de7-11e5-84da-df2ce0515411.png)

**Comment by jsiems** [comment]
fixed #61 
as of now, anybody can mark any comment as an issue. This will be brought up in a new issue post.
